package Formularios;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

import java.awt.SystemColor;
import java.awt.Toolkit;

import javax.swing.JLabel;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.imageio.ImageIO;
import javax.sql.rowset.serial.SerialBlob;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

import Clases.cls_repuestos;
import ComponenteOtros.metodos;
import ComponenteOtros.mipanel;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;

import javax.swing.JTable;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.SwingConstants;

public class frm_repuestos extends JFrame {
	
	private int bandera;
	


	private JPanel contentPane;
	private JTextField txtPrecio;
	private JTextField txtNombre;
	private JTable tabla1;
	private JTextField txtN;
	private JButton btnExaminar;
	private JButton btnActualizar;
	private JButton btnGuardar;
	private JButton btnEliminar;
	private JButton btnCancelar;
	private JButton btnAgregar;
	private JTextField txtIDre;
	private JPanel JPimg;
	private JLabel imagen1;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					frm_repuestos frame = new frm_repuestos();
					frame.setVisible(true);
					frame.setLocationRelativeTo(null);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public frm_repuestos() {
		this.setUndecorated(true);
		setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\hp\\Desktop\\iconos aplicaciones\\mecanica\\coche.png"));
		
		
		 String ImagenURL;

		    /** This method is called from within the constructor to
		     * initialize the form.
		     * WARNING: Do NOT modify this code. The content of this method is
		     * always regenerated by the Form Editor.
		     */
		    
		
		
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowOpened(WindowEvent arg0) {
				bcajas();
				cls_repuestos rep = new cls_repuestos();
				 String[] cabecera={"idRepuesto","Nombre","Precio","Stock"};
					Object datos[][]=rep.consultar(txtN.getText());
					tabla1.setModel(new DefaultTableModel(datos,cabecera) );
					
					btnExaminar.setVisible(false);
					JPimg.setVisible(false);
					txtIDre.setVisible(false);
					imagen1.setVisible(false);
					bcajas();
					bbotones();
					btnAgregar.setEnabled(true);
					bandera=0;
			}
		});
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 695, 684);
		contentPane = new JPanel();
		contentPane.setBackground(SystemColor.info);
		contentPane.setBorder(new LineBorder(SystemColor.textHighlight, 3));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JLabel lblRepuestos = new JLabel("REPUESTOS");
		lblRepuestos.setForeground(Color.RED);
		lblRepuestos.setFont(new Font("Comic Sans MS", Font.BOLD, 24));
		lblRepuestos.setBackground(Color.BLUE);
		lblRepuestos.setBounds(267, 10, 176, 34);
		contentPane.add(lblRepuestos);
		
		JLabel lblListadoDeRepuestos = new JLabel("Listado de repuestos:");
		lblListadoDeRepuestos.setForeground(SystemColor.desktop);
		lblListadoDeRepuestos.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
		lblListadoDeRepuestos.setBackground(SystemColor.controlText);
		lblListadoDeRepuestos.setBounds(10, 220, 155, 34);
		contentPane.add(lblListadoDeRepuestos);
		
		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(20, 255, 641, 303);
		contentPane.add(scrollPane);
		
		tabla1 = new JTable();
		tabla1.setFont(new Font("Tahoma", Font.BOLD, 18));
		tabla1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				
				cls_repuestos re = new cls_repuestos();
				String datos[] = null;
				DefaultTableModel tm = (DefaultTableModel) tabla1.getModel();
				String codigo=String.valueOf(tm.getValueAt(tabla1.getSelectedRow(),0));
				datos=re.datoRe(codigo);
			
				txtIDre.setText(datos[0]);
				txtNombre.setText(datos[1]);
				txtPrecio.setText(datos[2]);
				
				bbotones();
				btnActualizar.setEnabled(true);
				btnCancelar.setEnabled(true);
				btnEliminar.setEnabled(true);
				
				
				try {
					imagen1.setIcon((Icon) re.abrirImagen());
				} catch (SQLException | IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				
				
				
				
				
				
				
				/*
				Blob aBlob = re.getFoto();
				InputStream is = null;
				try {
					is = aBlob.getBinaryStream(0, aBlob.length());
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				BufferedImage imag = null;
				try {
					imag = ImageIO.read(is);
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				
				Image image = imag;
				ImageIcon icon =new ImageIcon(image);
				imagen1.setIcon(icon); 
			*/

				
				

			}
			
		});
		scrollPane.setViewportView(tabla1);
		
		btnActualizar = new JButton("Actualizar");
		btnActualizar.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\iconos aplicaciones\\mecanica\\menu\\actualizar.png"));
		btnActualizar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				acajas();
				bbotones();
				btnGuardar.setEnabled(true);
				btnCancelar.setEnabled(true);
				bandera=2;
				
			}
		});
		btnActualizar.setForeground(SystemColor.textHighlight);
		btnActualizar.setFont(new Font("Comic Sans MS", Font.BOLD, 15));
		btnActualizar.setBounds(259, 64, 153, 39);
		contentPane.add(btnActualizar);
		
		btnGuardar = new JButton("Guardar");
		btnGuardar.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\iconos aplicaciones\\mecanica\\menu\\disquete.png"));
		btnGuardar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				cls_repuestos re = new cls_repuestos();
				
				re.setNombre(txtNombre.getText());
				re.setPrecio(Double.parseDouble(txtPrecio.getText().toString()));
				re.setCodigo(txtIDre.getText());
				re.setFoto(imgURL);
				
				if(bandera==1){
					
					if(re. insertar()==true){
					
					JOptionPane.showMessageDialog(null,"Registro Guardado");
				}
				
				else{
					JOptionPane.showMessageDialog(null, "Error al Registrar");
				  }
				}
				
				if(bandera==2){
					if(re.actualizar()==true){
						
						JOptionPane.showMessageDialog(null,"Registro Actualizado");
					}
					
					else{
						JOptionPane.showMessageDialog(null, "Error al Actualizar");
					  }
					
				}
				    bandera=0;
				    lcajas();
					bcajas();
					bbotones();
				    btnAgregar.setEnabled(true);
				
			}
				
			
		});
		btnGuardar.setForeground(SystemColor.textHighlight);
		btnGuardar.setFont(new Font("Comic Sans MS", Font.BOLD, 15));
		btnGuardar.setBounds(420, 64, 134, 39);
		contentPane.add(btnGuardar);
		
		btnCancelar = new JButton("Cancelar");
		btnCancelar.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\iconos aplicaciones\\mecanica\\menu\\cancelar.png"));
		btnCancelar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				
				bcajas();
				lcajas();
				bbotones();
				btnAgregar.setEnabled(true);
			}
		});
		btnCancelar.setForeground(SystemColor.textHighlight);
		btnCancelar.setFont(new Font("Comic Sans MS", Font.BOLD, 15));
		btnCancelar.setBounds(193, 110, 134, 39);
		contentPane.add(btnCancelar);
		
		btnEliminar = new JButton("Eliminar");
		btnEliminar.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\iconos aplicaciones\\mecanica\\menu\\goma-de-borrar.png"));
		btnEliminar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {

				cls_repuestos r = new cls_repuestos();
				
				r.setCodigo(txtIDre.getText());
				if(r.Eliminar()) {
					JOptionPane.showMessageDialog(null, "Registro Eliminado");
				}else {
					JOptionPane.showMessageDialog(null, "Error al Eliminar");
				}
				
				/*bcajas();
				bbotones();
				bcajas();*/
			}
		});
		btnEliminar.setForeground(SystemColor.textHighlight);
		btnEliminar.setFont(new Font("Comic Sans MS", Font.BOLD, 15));
		btnEliminar.setBounds(337, 110, 134, 39);
		contentPane.add(btnEliminar);
		
		JPanel panel = new JPanel();
		panel.setBackground(SystemColor.scrollbar);
		panel.setBounds(10, 569, 651, 92);
		contentPane.add(panel);
		panel.setLayout(null);
		
		JLabel lblNuevoRepuesto = new JLabel("Nuevo Repuesto:");
		lblNuevoRepuesto.setBounds(10, 0, 123, 23);
		lblNuevoRepuesto.setForeground(SystemColor.desktop);
		lblNuevoRepuesto.setFont(new Font("Comic Sans MS", Font.PLAIN, 15));
		lblNuevoRepuesto.setBackground(Color.BLUE);
		panel.add(lblNuevoRepuesto);
		
		JLabel label_1 = new JLabel("Nombre:");
		label_1.setBounds(187, 11, 381, 34);
		panel.add(label_1);
		label_1.setForeground(new Color(0, 0, 139));
		label_1.setFont(new Font("Comic Sans MS", Font.BOLD, 17));
		label_1.setBackground(Color.BLUE);
		
		txtNombre = new JTextField();
		txtNombre.setBounds(260, 17, 308, 26);
		panel.add(txtNombre);
		txtNombre.setFont(new Font("Comic Sans MS", Font.BOLD, 12));
		txtNombre.setColumns(10);
		
		JLabel lblPrecio = new JLabel("Precio:");
		lblPrecio.setBounds(291, 42, 70, 34);
		panel.add(lblPrecio);
		lblPrecio.setForeground(new Color(0, 0, 139));
		lblPrecio.setFont(new Font("Comic Sans MS", Font.BOLD, 17));
		lblPrecio.setBackground(Color.BLUE);
		
		txtPrecio = new JTextField();
		txtPrecio.setBounds(353, 48, 117, 26);
		panel.add(txtPrecio);
		txtPrecio.setFont(new Font("Comic Sans MS", Font.BOLD, 12));
		txtPrecio.setColumns(10);
		
		txtN = new JTextField();
		txtN.addKeyListener(new KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent arg0) {
				cls_repuestos rep = new cls_repuestos();
				 String[] cabecera={"idRepuesto","Nombre","Precio","Stock"," Imagen"};
					Object datos[][]=rep.consultar(txtN.getText());
					tabla1.setModel(new DefaultTableModel(datos,cabecera) );
				
				
			}
		});
		txtN.setFont(new Font("Comic Sans MS", Font.BOLD, 12));
		txtN.setColumns(10);
		txtN.setBounds(316, 229, 149, 19);
		contentPane.add(txtN);
		
		JLabel lblBuscar = new JLabel("Buscar:");
		lblBuscar.setForeground(new Color(0, 0, 153));
		lblBuscar.setFont(new Font("Comic Sans MS", Font.PLAIN, 16));
		lblBuscar.setBackground(Color.BLUE);
		lblBuscar.setBounds(260, 220, 61, 34);
		contentPane.add(lblBuscar);
		
		btnAgregar = new JButton("Agregar");
		btnAgregar.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\iconos aplicaciones\\mecanica\\menu\\archivo.png"));
		btnAgregar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				acajas();
				bbotones();
				btnGuardar.setEnabled(true);
				btnCancelar.setEnabled(true);
				bandera=1;
			}
		});
		btnAgregar.setForeground(SystemColor.textHighlight);
		btnAgregar.setFont(new Font("Comic Sans MS", Font.BOLD, 15));
		btnAgregar.setBounds(115, 64, 134, 39);
		contentPane.add(btnAgregar);
		
		txtIDre = new JTextField();
		txtIDre.setEnabled(false);
		txtIDre.setFont(new Font("Comic Sans MS", Font.BOLD, 12));
		txtIDre.setColumns(10);
		txtIDre.setBounds(20, 123, 53, 26);
		contentPane.add(txtIDre);
		
		JPimg = new JPanel();
		JPimg.setBackground(UIManager.getColor("Button.light"));
		JPimg.setBounds(548, 109, 125, 100);
		contentPane.add(JPimg);
		JPimg.setLayout(null);
		
		btnExaminar = new JButton("examinar");
		btnExaminar.setFont(new Font("Comic Sans MS", Font.PLAIN, 13));
		btnExaminar.setBounds(572, 220, 89, 23);
		contentPane.add(btnExaminar);
		
		imagen1 = new JLabel("New label");
		imagen1.setIcon(new ImageIcon(frm_repuestos.class.getResource("/imagenes/cancel.png")));
		imagen1.setBounds(10, 15, 62, 57);
		contentPane.add(imagen1);
		
		button = new JButton("");
		button.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\iconos aplicaciones\\mecanica\\menu\\flecha-hacia-la-izquierda (1).png"));
		button.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				hide();
			}
		});
		button.setForeground(new Color(0, 0, 205));
		button.setFont(new Font("Comic Sans MS", Font.BOLD, 15));
		button.setBounds(612, 15, 61, 60);
		contentPane.add(button);
		
		label = new JLabel("");
		label.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\iconos aplicaciones\\mecanica\\menu\\ajustes.png"));
		label.setForeground(Color.RED);
		label.setFont(new Font("Comic Sans MS", Font.BOLD, 24));
		label.setBackground(Color.BLUE);
		label.setBounds(229, 10, 47, 34);
		contentPane.add(label);
		btnExaminar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				JPimg.removeAll();
		        m.Abrir_Dialogo(JPimg);
		        imgURL = m.ObtenerUrl();
		        
		        
;			}
		});
	}
	
	public void acajas(){
		txtNombre.setEnabled(true);
		txtPrecio.setEnabled(true);
	}
	
	public void bcajas(){
		txtNombre.setEnabled(false);
		txtPrecio.setEnabled(false);
	}
	public void lcajas(){
		txtNombre.setText("");
		txtPrecio.setText("");
	}
	public void bbotones(){
		btnAgregar.setEnabled(false);
		btnGuardar.setEnabled(false);
		btnActualizar.setEnabled(false);
		btnEliminar.setEnabled(false);
		btnCancelar.setEnabled(false);
	}
	
	
	
	 metodos m = new metodos() {
	    };
	    String imgURL;
	    private JButton button;
	    private JLabel label;
	public void Mostrar(JPanel p) {
        try {
            //Asigna a "URL" el archivo de imagen seleccionado
            URL url = m.getObtener();
            //Coloca en memoria
            m.cargar_imagen(url);
            //se añade al contenedor
            p.add(new mipanel(m.Obtener_imagen_de_Buffer(), p.getSize()) {
            });
            p.setVisible(true);
            p.repaint();
        } catch (Exception ex) {
            Logger.getLogger(metodos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
	
	
	

}
